#! /bin/sh

export PATH=$PATH:$HOME/.config/bspwm

bspc config border_width 2
bspc config window_gap 10
bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config normal_border_color "#839496"
bspc config focused_border_color "#268BD2"
bspc config presel_feedback_color "#268BD2"

bspc monitor -d 1 2 3 4 5 6

hsetroot -solid "#002B36"
compton -b &
panel &




